CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_KEYBOARD_REPORT_QUEUE_SIZE=20
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Stage 2A WS2812 LED test
